import "../styles/globals.css";
import "windi.css";
import ClientLayout from "./client-layout.tsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh">
      <body>
        {/* 用 client layout 包裹所有 children，实现前端守卫 */}
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
