import "../styles/globals.css";
import "windi.css";
import ClientLayout from "./client-layout";
import { Playfair_Display } from "next/font/google";

// 导入 Playfair Display 字体
const playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playfair",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh" className={`${playfair.variable}`}>
      <body>
        {/* 用 client layout 包裹所有 children，实现前端守卫 */}
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
